// lib/data/sample_data.dart

import '../models/employee.dart';

final List<Employee> sampleEmployees = [
  // C-Suite
  Employee(
    id: 'E001',
    name: 'Arjun Sharma',
    department: 'Executive',
    designation: Designation.ceo,
    phoneNumber: '+880 1711-000001',
    landlineShortNumber: '100',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'arjun.sharma@company.com',
    emergencyContactName: 'Priya Sharma',
    emergencyContactPhone: '+880 1711-100001',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E002',
    name: 'Fatema Begum',
    department: 'Operations',
    designation: Designation.coo,
    phoneNumber: '+880 1711-000002',
    landlineShortNumber: '101',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'fatema.begum@company.com',
    emergencyContactName: 'Karim Begum',
    emergencyContactPhone: '+880 1711-100002',
    emergencyContactRelation: 'Spouse',
  ),

  // Senior Managers
  Employee(
    id: 'E003',
    name: 'Rahim Chowdhury',
    department: 'Finance',
    designation: Designation.seniorManager,
    phoneNumber: '+880 1711-000003',
    landlineShortNumber: '201',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'rahim.chowdhury@company.com',
    emergencyContactName: 'Nasrin Chowdhury',
    emergencyContactPhone: '+880 1711-100003',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E004',
    name: 'Salma Khatun',
    department: 'Human Resources',
    designation: Designation.seniorManager,
    phoneNumber: '+880 1711-000004',
    landlineShortNumber: '202',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onLeave,
    email: 'salma.khatun@company.com',
    emergencyContactName: 'Habib Khatun',
    emergencyContactPhone: '+880 1711-100004',
    emergencyContactRelation: 'Father',
  ),
  Employee(
    id: 'E005',
    name: 'Imran Hassan',
    department: 'Information Technology',
    designation: Designation.seniorManager,
    phoneNumber: '+880 1711-000005',
    landlineShortNumber: '203',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'imran.hassan@company.com',
    emergencyContactName: 'Roksana Hassan',
    emergencyContactPhone: '+880 1711-100005',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E006',
    name: 'Nasrin Akter',
    department: 'Marketing',
    designation: Designation.seniorManager,
    phoneNumber: '+880 1711-000006',
    landlineShortNumber: '204',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.home,
    email: 'nasrin.akter@company.com',
    emergencyContactName: 'Kabir Akter',
    emergencyContactPhone: '+880 1711-100006',
    emergencyContactRelation: 'Brother',
  ),

  // Managers
  Employee(
    id: 'E007',
    name: 'Kabir Ahmed',
    department: 'Finance',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000007',
    landlineShortNumber: '301',
    bloodGroup: BloodGroup.aNegative,
    status: EmployeeStatus.onDuty,
    email: 'kabir.ahmed@company.com',
    emergencyContactName: 'Dilara Ahmed',
    emergencyContactPhone: '+880 1711-100007',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E008',
    name: 'Dilara Islam',
    department: 'Human Resources',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000008',
    landlineShortNumber: '302',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'dilara.islam@company.com',
    emergencyContactName: 'Rafiq Islam',
    emergencyContactPhone: '+880 1711-100008',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E009',
    name: 'Shahriar Khan',
    department: 'Information Technology',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000009',
    landlineShortNumber: '303',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onLeave,
    email: 'shahriar.khan@company.com',
    emergencyContactName: 'Mitu Khan',
    emergencyContactPhone: '+880 1711-100009',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E010',
    name: 'Mitu Rahman',
    department: 'Marketing',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000010',
    landlineShortNumber: '304',
    bloodGroup: BloodGroup.abNegative,
    status: EmployeeStatus.onDuty,
    email: 'mitu.rahman@company.com',
    emergencyContactName: 'Jalal Rahman',
    emergencyContactPhone: '+880 1711-100010',
    emergencyContactRelation: 'Father',
  ),
  Employee(
    id: 'E011',
    name: 'Jalal Uddin',
    department: 'Sales',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000011',
    landlineShortNumber: '305',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'jalal.uddin@company.com',
    emergencyContactName: 'Sumaiya Uddin',
    emergencyContactPhone: '+880 1711-100011',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E012',
    name: 'Sumaiya Parvin',
    department: 'Administration',
    designation: Designation.manager,
    phoneNumber: '+880 1711-000012',
    landlineShortNumber: '306',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'sumaiya.parvin@company.com',
    emergencyContactName: 'Ruhul Parvin',
    emergencyContactPhone: '+880 1711-100012',
    emergencyContactRelation: 'Spouse',
  ),

  // Deputy Managers
  Employee(
    id: 'E013',
    name: 'Ruhul Amin',
    department: 'Finance',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000013',
    landlineShortNumber: '401',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'ruhul.amin@company.com',
    emergencyContactName: 'Shirin Amin',
    emergencyContactPhone: '+880 1711-100013',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E014',
    name: 'Shirin Sultana',
    department: 'Human Resources',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000014',
    landlineShortNumber: '402',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'shirin.sultana@company.com',
    emergencyContactName: 'Kamrul Sultana',
    emergencyContactPhone: '+880 1711-100014',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E015',
    name: 'Kamrul Islam',
    department: 'Information Technology',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000015',
    landlineShortNumber: '403',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onLeave,
    email: 'kamrul.islam@company.com',
    emergencyContactName: 'Tania Islam',
    emergencyContactPhone: '+880 1711-100015',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E016',
    name: 'Tania Akter',
    department: 'Marketing',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000016',
    landlineShortNumber: '404',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onDuty,
    email: 'tania.akter@company.com',
    emergencyContactName: 'Forhad Akter',
    emergencyContactPhone: '+880 1711-100016',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E017',
    name: 'Forhad Hossain',
    department: 'Sales',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000017',
    landlineShortNumber: '405',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onDuty,
    email: 'forhad.hossain@company.com',
    emergencyContactName: 'Lima Hossain',
    emergencyContactPhone: '+880 1711-100017',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E018',
    name: 'Lima Begum',
    department: 'Administration',
    designation: Designation.deputyManager,
    phoneNumber: '+880 1711-000018',
    landlineShortNumber: '406',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.home,
    email: 'lima.begum@company.com',
    emergencyContactName: 'Zahir Begum',
    emergencyContactPhone: '+880 1711-100018',
    emergencyContactRelation: 'Spouse',
  ),

  // Assistants
  Employee(
    id: 'E019',
    name: 'Zahirul Haque',
    department: 'Finance',
    designation: Designation.assistant,
    phoneNumber: '+880 1711-000019',
    landlineShortNumber: '501',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'zahirul.haque@company.com',
    emergencyContactName: 'Monika Haque',
    emergencyContactPhone: '+880 1711-100019',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E020',
    name: 'Monika Rani',
    department: 'Human Resources',
    designation: Designation.assistant,
    phoneNumber: '+880 1711-000020',
    landlineShortNumber: '502',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'monika.rani@company.com',
    emergencyContactName: 'Sujon Rani',
    emergencyContactPhone: '+880 1711-100020',
    emergencyContactRelation: 'Brother',
  ),
  Employee(
    id: 'E021',
    name: 'Sujon Das',
    department: 'Information Technology',
    designation: Designation.assistant,
    phoneNumber: '+880 1711-000021',
    landlineShortNumber: '503',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onLeave,
    email: 'sujon.das@company.com',
    emergencyContactName: 'Puja Das',
    emergencyContactPhone: '+880 1711-100021',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E022',
    name: 'Puja Saha',
    department: 'Marketing',
    designation: Designation.assistant,
    phoneNumber: '+880 1711-000022',
    landlineShortNumber: '504',
    bloodGroup: BloodGroup.abNegative,
    status: EmployeeStatus.onDuty,
    email: 'puja.saha@company.com',
    emergencyContactName: 'Nikhil Saha',
    emergencyContactPhone: '+880 1711-100022',
    emergencyContactRelation: 'Father',
  ),
  Employee(
    id: 'E023',
    name: 'Nikhil Paul',
    department: 'Sales',
    designation: Designation.assistant,
    phoneNumber: '+880 1711-000023',
    landlineShortNumber: '505',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'nikhil.paul@company.com',
    emergencyContactName: 'Rekha Paul',
    emergencyContactPhone: '+880 1711-100023',
    emergencyContactRelation: 'Spouse',
  ),

  // Senior Executives
  Employee(
    id: 'E024',
    name: 'Rekha Roy',
    department: 'Finance',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000024',
    landlineShortNumber: '601',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'rekha.roy@company.com',
    emergencyContactName: 'Bikash Roy',
    emergencyContactPhone: '+880 1711-100024',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E025',
    name: 'Bikash Barua',
    department: 'Human Resources',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000025',
    landlineShortNumber: '602',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.home,
    email: 'bikash.barua@company.com',
    emergencyContactName: 'Lipika Barua',
    emergencyContactPhone: '+880 1711-100025',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E026',
    name: 'Lipika Dey',
    department: 'Information Technology',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000026',
    landlineShortNumber: '603',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'lipika.dey@company.com',
    emergencyContactName: 'Ripon Dey',
    emergencyContactPhone: '+880 1711-100026',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E027',
    name: 'Ripon Mia',
    department: 'Marketing',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000027',
    landlineShortNumber: '604',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onDuty,
    email: 'ripon.mia@company.com',
    emergencyContactName: 'Bina Mia',
    emergencyContactPhone: '+880 1711-100027',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E028',
    name: 'Bina Khanam',
    department: 'Sales',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000028',
    landlineShortNumber: '605',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onLeave,
    email: 'bina.khanam@company.com',
    emergencyContactName: 'Rafiqul Khanam',
    emergencyContactPhone: '+880 1711-100028',
    emergencyContactRelation: 'Father',
  ),
  Employee(
    id: 'E029',
    name: 'Rafiqul Alam',
    department: 'Administration',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000029',
    landlineShortNumber: '606',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'rafiqul.alam@company.com',
    emergencyContactName: 'Champa Alam',
    emergencyContactPhone: '+880 1711-100029',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E030',
    name: 'Champa Rani',
    department: 'Finance',
    designation: Designation.seniorExecutive,
    phoneNumber: '+880 1711-000030',
    landlineShortNumber: '607',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'champa.rani@company.com',
    emergencyContactName: 'Tapan Rani',
    emergencyContactPhone: '+880 1711-100030',
    emergencyContactRelation: 'Spouse',
  ),

  // Executives (E031 - E065)
  Employee(
    id: 'E031',
    name: 'Tapan Kumar',
    department: 'Finance',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000031',
    landlineShortNumber: '701',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'tapan.kumar@company.com',
    emergencyContactName: 'Anjali Kumar',
    emergencyContactPhone: '+880 1711-100031',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E032',
    name: 'Anjali Das',
    department: 'Human Resources',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000032',
    landlineShortNumber: '702',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'anjali.das@company.com',
    emergencyContactName: 'Suman Das',
    emergencyContactPhone: '+880 1711-100032',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E033',
    name: 'Suman Sarkar',
    department: 'Information Technology',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000033',
    landlineShortNumber: '703',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'suman.sarkar@company.com',
    emergencyContactName: 'Priti Sarkar',
    emergencyContactPhone: '+880 1711-100033',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E034',
    name: 'Priti Mondal',
    department: 'Marketing',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000034',
    landlineShortNumber: '704',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onDuty,
    email: 'priti.mondal@company.com',
    emergencyContactName: 'Sanjay Mondal',
    emergencyContactPhone: '+880 1711-100034',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E035',
    name: 'Sanjay Ghosh',
    department: 'Sales',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000035',
    landlineShortNumber: '705',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onLeave,
    email: 'sanjay.ghosh@company.com',
    emergencyContactName: 'Mala Ghosh',
    emergencyContactPhone: '+880 1711-100035',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E036',
    name: 'Mala Biswas',
    department: 'Administration',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000036',
    landlineShortNumber: '706',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'mala.biswas@company.com',
    emergencyContactName: 'Tapas Biswas',
    emergencyContactPhone: '+880 1711-100036',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E037',
    name: 'Tapas Chakraborty',
    department: 'Finance',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000037',
    landlineShortNumber: '707',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'tapas.chakraborty@company.com',
    emergencyContactName: 'Sunita Chakraborty',
    emergencyContactPhone: '+880 1711-100037',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E038',
    name: 'Sunita Dutta',
    department: 'Human Resources',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000038',
    landlineShortNumber: '708',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'sunita.dutta@company.com',
    emergencyContactName: 'Arup Dutta',
    emergencyContactPhone: '+880 1711-100038',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E039',
    name: 'Arup Nath',
    department: 'Information Technology',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000039',
    landlineShortNumber: '709',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'arup.nath@company.com',
    emergencyContactName: 'Swati Nath',
    emergencyContactPhone: '+880 1711-100039',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E040',
    name: 'Swati Sen',
    department: 'Marketing',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000040',
    landlineShortNumber: '710',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.home,
    email: 'swati.sen@company.com',
    emergencyContactName: 'Debashis Sen',
    emergencyContactPhone: '+880 1711-100040',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E041',
    name: 'Debashis Pal',
    department: 'Sales',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000041',
    landlineShortNumber: '711',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'debashis.pal@company.com',
    emergencyContactName: 'Rupa Pal',
    emergencyContactPhone: '+880 1711-100041',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E042',
    name: 'Rupa Basak',
    department: 'Administration',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000042',
    landlineShortNumber: '712',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onLeave,
    email: 'rupa.basak@company.com',
    emergencyContactName: 'Prokash Basak',
    emergencyContactPhone: '+880 1711-100042',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E043',
    name: 'Prokash Bose',
    department: 'Finance',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000043',
    landlineShortNumber: '713',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'prokash.bose@company.com',
    emergencyContactName: 'Ira Bose',
    emergencyContactPhone: '+880 1711-100043',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E044',
    name: 'Ira Adhikary',
    department: 'Human Resources',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000044',
    landlineShortNumber: '714',
    bloodGroup: BloodGroup.aNegative,
    status: EmployeeStatus.onDuty,
    email: 'ira.adhikary@company.com',
    emergencyContactName: 'Goutam Adhikary',
    emergencyContactPhone: '+880 1711-100044',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E045',
    name: 'Goutam Halder',
    department: 'Information Technology',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000045',
    landlineShortNumber: '715',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'goutam.halder@company.com',
    emergencyContactName: 'Mamata Halder',
    emergencyContactPhone: '+880 1711-100045',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E046',
    name: 'Mamata Gain',
    department: 'Marketing',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000046',
    landlineShortNumber: '716',
    bloodGroup: BloodGroup.abNegative,
    status: EmployeeStatus.home,
    email: 'mamata.gain@company.com',
    emergencyContactName: 'Subhash Gain',
    emergencyContactPhone: '+880 1711-100046',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E047',
    name: 'Subhash Karmakar',
    department: 'Sales',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000047',
    landlineShortNumber: '717',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'subhash.karmakar@company.com',
    emergencyContactName: 'Kakoli Karmakar',
    emergencyContactPhone: '+880 1711-100047',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E048',
    name: 'Kakoli Majumdar',
    department: 'Administration',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000048',
    landlineShortNumber: '718',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'kakoli.majumdar@company.com',
    emergencyContactName: 'Dipak Majumdar',
    emergencyContactPhone: '+880 1711-100048',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E049',
    name: 'Dipak Mukherjee',
    department: 'Finance',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000049',
    landlineShortNumber: '719',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onLeave,
    email: 'dipak.mukherjee@company.com',
    emergencyContactName: 'Sujata Mukherjee',
    emergencyContactPhone: '+880 1711-100049',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E050',
    name: 'Sujata Kundu',
    department: 'Human Resources',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000050',
    landlineShortNumber: '720',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'sujata.kundu@company.com',
    emergencyContactName: 'Niladri Kundu',
    emergencyContactPhone: '+880 1711-100050',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E051',
    name: 'Niladri Mitra',
    department: 'Information Technology',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000051',
    landlineShortNumber: '721',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'niladri.mitra@company.com',
    emergencyContactName: 'Tapati Mitra',
    emergencyContactPhone: '+880 1711-100051',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E052',
    name: 'Tapati Chandra',
    department: 'Marketing',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000052',
    landlineShortNumber: '722',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.home,
    email: 'tapati.chandra@company.com',
    emergencyContactName: 'Samar Chandra',
    emergencyContactPhone: '+880 1711-100052',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E053',
    name: 'Samar Guha',
    department: 'Sales',
    designation: Designation.executive,
    phoneNumber: '+880 1711-000053',
    landlineShortNumber: '723',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'samar.guha@company.com',
    emergencyContactName: 'Bandana Guha',
    emergencyContactPhone: '+880 1711-100053',
    emergencyContactRelation: 'Spouse',
  ),

  // Junior Executives (E054 - E100)
  Employee(
    id: 'E054',
    name: 'Bandana Roy',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000054',
    landlineShortNumber: '801',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'bandana.roy@company.com',
    emergencyContactName: 'Arnab Roy',
    emergencyContactPhone: '+880 1711-100054',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E055',
    name: 'Arnab Dey',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000055',
    landlineShortNumber: '802',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onLeave,
    email: 'arnab.dey@company.com',
    emergencyContactName: 'Rimpa Dey',
    emergencyContactPhone: '+880 1711-100055',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E056',
    name: 'Rimpa Ghosh',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000056',
    landlineShortNumber: '803',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'rimpa.ghosh@company.com',
    emergencyContactName: 'Rohit Ghosh',
    emergencyContactPhone: '+880 1711-100056',
    emergencyContactRelation: 'Brother',
  ),
  Employee(
    id: 'E057',
    name: 'Rohit Saha',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000057',
    landlineShortNumber: '804',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onDuty,
    email: 'rohit.saha@company.com',
    emergencyContactName: 'Sudha Saha',
    emergencyContactPhone: '+880 1711-100057',
    emergencyContactRelation: 'Mother',
  ),
  Employee(
    id: 'E058',
    name: 'Sudha Rani',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000058',
    landlineShortNumber: '805',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.home,
    email: 'sudha.rani@company.com',
    emergencyContactName: 'Manoj Rani',
    emergencyContactPhone: '+880 1711-100058',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E059',
    name: 'Manoj Kumar',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000059',
    landlineShortNumber: '806',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'manoj.kumar@company.com',
    emergencyContactName: 'Geeta Kumar',
    emergencyContactPhone: '+880 1711-100059',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E060',
    name: 'Geeta Sharma',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000060',
    landlineShortNumber: '807',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'geeta.sharma@company.com',
    emergencyContactName: 'Vikas Sharma',
    emergencyContactPhone: '+880 1711-100060',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E061',
    name: 'Vikas Singh',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000061',
    landlineShortNumber: '808',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onLeave,
    email: 'vikas.singh@company.com',
    emergencyContactName: 'Pooja Singh',
    emergencyContactPhone: '+880 1711-100061',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E062',
    name: 'Pooja Verma',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000062',
    landlineShortNumber: '809',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'pooja.verma@company.com',
    emergencyContactName: 'Rahul Verma',
    emergencyContactPhone: '+880 1711-100062',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E063',
    name: 'Rahul Gupta',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000063',
    landlineShortNumber: '810',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onDuty,
    email: 'rahul.gupta@company.com',
    emergencyContactName: 'Kavita Gupta',
    emergencyContactPhone: '+880 1711-100063',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E064',
    name: 'Kavita Joshi',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000064',
    landlineShortNumber: '811',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'kavita.joshi@company.com',
    emergencyContactName: 'Pradeep Joshi',
    emergencyContactPhone: '+880 1711-100064',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E065',
    name: 'Pradeep Mishra',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000065',
    landlineShortNumber: '812',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onDuty,
    email: 'pradeep.mishra@company.com',
    emergencyContactName: 'Deepa Mishra',
    emergencyContactPhone: '+880 1711-100065',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E066',
    name: 'Deepa Pandey',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000066',
    landlineShortNumber: '813',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'deepa.pandey@company.com',
    emergencyContactName: 'Ravi Pandey',
    emergencyContactPhone: '+880 1711-100066',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E067',
    name: 'Ravi Shankar',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000067',
    landlineShortNumber: '814',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onLeave,
    email: 'ravi.shankar@company.com',
    emergencyContactName: 'Laxmi Shankar',
    emergencyContactPhone: '+880 1711-100067',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E068',
    name: 'Laxmi Devi',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000068',
    landlineShortNumber: '815',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'laxmi.devi@company.com',
    emergencyContactName: 'Suresh Devi',
    emergencyContactPhone: '+880 1711-100068',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E069',
    name: 'Suresh Yadav',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000069',
    landlineShortNumber: '816',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'suresh.yadav@company.com',
    emergencyContactName: 'Meena Yadav',
    emergencyContactPhone: '+880 1711-100069',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E070',
    name: 'Meena Kumari',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000070',
    landlineShortNumber: '817',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'meena.kumari@company.com',
    emergencyContactName: 'Ashok Kumari',
    emergencyContactPhone: '+880 1711-100070',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E071',
    name: 'Ashok Tiwari',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000071',
    landlineShortNumber: '818',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'ashok.tiwari@company.com',
    emergencyContactName: 'Sonia Tiwari',
    emergencyContactPhone: '+880 1711-100071',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E072',
    name: 'Sonia Chauhan',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000072',
    landlineShortNumber: '819',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'sonia.chauhan@company.com',
    emergencyContactName: 'Pawan Chauhan',
    emergencyContactPhone: '+880 1711-100072',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E073',
    name: 'Pawan Rajput',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000073',
    landlineShortNumber: '820',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.onLeave,
    email: 'pawan.rajput@company.com',
    emergencyContactName: 'Sunita Rajput',
    emergencyContactPhone: '+880 1711-100073',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E074',
    name: 'Sunita Nair',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000074',
    landlineShortNumber: '821',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onDuty,
    email: 'sunita.nair@company.com',
    emergencyContactName: 'Sreejith Nair',
    emergencyContactPhone: '+880 1711-100074',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E075',
    name: 'Sreejith Pillai',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000075',
    landlineShortNumber: '822',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'sreejith.pillai@company.com',
    emergencyContactName: 'Divya Pillai',
    emergencyContactPhone: '+880 1711-100075',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E076',
    name: 'Divya Menon',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000076',
    landlineShortNumber: '823',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'divya.menon@company.com',
    emergencyContactName: 'Vishnu Menon',
    emergencyContactPhone: '+880 1711-100076',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E077',
    name: 'Vishnu Reddy',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000077',
    landlineShortNumber: '824',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'vishnu.reddy@company.com',
    emergencyContactName: 'Anitha Reddy',
    emergencyContactPhone: '+880 1711-100077',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E078',
    name: 'Anitha Krishnan',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000078',
    landlineShortNumber: '825',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'anitha.krishnan@company.com',
    emergencyContactName: 'Murugan Krishnan',
    emergencyContactPhone: '+880 1711-100078',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E079',
    name: 'Murugan Rajan',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000079',
    landlineShortNumber: '826',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onLeave,
    email: 'murugan.rajan@company.com',
    emergencyContactName: 'Lakshmi Rajan',
    emergencyContactPhone: '+880 1711-100079',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E080',
    name: 'Lakshmi Narayanan',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000080',
    landlineShortNumber: '827',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'lakshmi.narayanan@company.com',
    emergencyContactName: 'Prabhakaran Narayanan',
    emergencyContactPhone: '+880 1711-100080',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E081',
    name: 'Prabhakaran Subramanian',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000081',
    landlineShortNumber: '828',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.onDuty,
    email: 'prabhakaran.subramanian@company.com',
    emergencyContactName: 'Radha Subramanian',
    emergencyContactPhone: '+880 1711-100081',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E082',
    name: 'Radha Chandran',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000082',
    landlineShortNumber: '829',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.home,
    email: 'radha.chandran@company.com',
    emergencyContactName: 'Gopalan Chandran',
    emergencyContactPhone: '+880 1711-100082',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E083',
    name: 'Gopalan Iyer',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000083',
    landlineShortNumber: '830',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'gopalan.iyer@company.com',
    emergencyContactName: 'Kamala Iyer',
    emergencyContactPhone: '+880 1711-100083',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E084',
    name: 'Kamala Subramaniam',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000084',
    landlineShortNumber: '831',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'kamala.subramaniam@company.com',
    emergencyContactName: 'Balaji Subramaniam',
    emergencyContactPhone: '+880 1711-100084',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E085',
    name: 'Balaji Venkatesh',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000085',
    landlineShortNumber: '832',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onLeave,
    email: 'balaji.venkatesh@company.com',
    emergencyContactName: 'Kavitha Venkatesh',
    emergencyContactPhone: '+880 1711-100085',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E086',
    name: 'Kavitha Ramachandran',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000086',
    landlineShortNumber: '833',
    bloodGroup: BloodGroup.bNegative,
    status: EmployeeStatus.onDuty,
    email: 'kavitha.ramachandran@company.com',
    emergencyContactName: 'Srinivasan Ramachandran',
    emergencyContactPhone: '+880 1711-100086',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E087',
    name: 'Srinivasan Ganapathy',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000087',
    landlineShortNumber: '834',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onDuty,
    email: 'srinivasan.ganapathy@company.com',
    emergencyContactName: 'Meenakshi Ganapathy',
    emergencyContactPhone: '+880 1711-100087',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E088',
    name: 'Meenakshi Sundaram',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000088',
    landlineShortNumber: '835',
    bloodGroup: BloodGroup.abPositive,
    status: EmployeeStatus.home,
    email: 'meenakshi.sundaram@company.com',
    emergencyContactName: 'Arunachalam Sundaram',
    emergencyContactPhone: '+880 1711-100088',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E089',
    name: 'Arunachalam Natarajan',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000089',
    landlineShortNumber: '836',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'arunachalam.natarajan@company.com',
    emergencyContactName: 'Saraswathi Natarajan',
    emergencyContactPhone: '+880 1711-100089',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E090',
    name: 'Saraswathi Gopal',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000090',
    landlineShortNumber: '837',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'saraswathi.gopal@company.com',
    emergencyContactName: 'Krishnaswamy Gopal',
    emergencyContactPhone: '+880 1711-100090',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E091',
    name: 'Krishnaswamy Seshadri',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000091',
    landlineShortNumber: '838',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onLeave,
    email: 'krishnaswamy.seshadri@company.com',
    emergencyContactName: 'Vimala Seshadri',
    emergencyContactPhone: '+880 1711-100091',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E092',
    name: 'Vimala Raghunathan',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000092',
    landlineShortNumber: '839',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'vimala.raghunathan@company.com',
    emergencyContactName: 'Parthasarathy Raghunathan',
    emergencyContactPhone: '+880 1711-100092',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E093',
    name: 'Parthasarathy Swaminathan',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000093',
    landlineShortNumber: '840',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'parthasarathy.swaminathan@company.com',
    emergencyContactName: 'Geetha Swaminathan',
    emergencyContactPhone: '+880 1711-100093',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E094',
    name: 'Geetha Murthy',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000094',
    landlineShortNumber: '841',
    bloodGroup: BloodGroup.oNegative,
    status: EmployeeStatus.home,
    email: 'geetha.murthy@company.com',
    emergencyContactName: 'Venkataraman Murthy',
    emergencyContactPhone: '+880 1711-100094',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E095',
    name: 'Venkataraman Thyagarajan',
    department: 'Administration',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000095',
    landlineShortNumber: '842',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'venkataraman.thyagarajan@company.com',
    emergencyContactName: 'Annapoorni Thyagarajan',
    emergencyContactPhone: '+880 1711-100095',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E096',
    name: 'Annapoorni Sivasubramanian',
    department: 'Finance',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000096',
    landlineShortNumber: '843',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'annapoorni.sivasubramanian@company.com',
    emergencyContactName: 'Thiruvenkatam Sivasubramanian',
    emergencyContactPhone: '+880 1711-100096',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E097',
    name: 'Thiruvenkatam Periyasamy',
    department: 'Human Resources',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000097',
    landlineShortNumber: '844',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.onLeave,
    email: 'thiruvenkatam.periyasamy@company.com',
    emergencyContactName: 'Ponnammal Periyasamy',
    emergencyContactPhone: '+880 1711-100097',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E098',
    name: 'Ponnammal Shanmugam',
    department: 'Information Technology',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000098',
    landlineShortNumber: '845',
    bloodGroup: BloodGroup.aPositive,
    status: EmployeeStatus.onDuty,
    email: 'ponnammal.shanmugam@company.com',
    emergencyContactName: 'Ramasamy Shanmugam',
    emergencyContactPhone: '+880 1711-100098',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E099',
    name: 'Ramasamy Velayutham',
    department: 'Marketing',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000099',
    landlineShortNumber: '846',
    bloodGroup: BloodGroup.bPositive,
    status: EmployeeStatus.onDuty,
    email: 'ramasamy.velayutham@company.com',
    emergencyContactName: 'Muthammal Velayutham',
    emergencyContactPhone: '+880 1711-100099',
    emergencyContactRelation: 'Spouse',
  ),
  Employee(
    id: 'E100',
    name: 'Muthammal Arumugam',
    department: 'Sales',
    designation: Designation.juniorExecutive,
    phoneNumber: '+880 1711-000100',
    landlineShortNumber: '847',
    bloodGroup: BloodGroup.oPositive,
    status: EmployeeStatus.home,
    email: 'muthammal.arumugam@company.com',
    emergencyContactName: 'Chinnaswamy Arumugam',
    emergencyContactPhone: '+880 1711-100100',
    emergencyContactRelation: 'Spouse',
  ),
];

final List<String> allDepartments = [
  'All Departments',
  'Executive',
  'Finance',
  'Human Resources',
  'Information Technology',
  'Marketing',
  'Sales',
  'Administration',
  'Operations',
];
